### ISSUE TITLE
Not all config features supported

### ISSUE THREAD

**Issue by nicorikken** [degville/woke-snap#1]
Thanks for packaging woke in the first place.
I tried to use it but ran into practical issues:

### Loading a config from the home directory
_Note that this is an explicit call. Normally this file should be used as fallback, but as Woke cannot access it, it is not used as fallback._
```
$ woke --debug -c ~/.woke.yaml 
2023-02-17T09:19:57+01:00 DBG woke version main built from 000000 on today
2023-02-17T09:19:57+01:00 DBG Adding custom ruleset from filename=/home/user/.woke.yaml
2023-02-17T09:19:57+01:00 DBG woke completed durationMS=0.018223
Error: open /home/user/.woke.yaml: permission denied
```

### Loading a config from the internet
```
$ woke --debug -c https://raw.githubusercontent.com/get-woke/woke/main/example.yaml
2023-02-17T09:31:35+01:00 DBG woke version main built from 000000 on today
2023-02-17T09:31:35+01:00 DBG Valid URL for remote config. remoteConfig=https://raw.githubusercontent.com/get-woke/woke/main/example.yaml
2023-02-17T09:31:35+01:00 DBG Downloading file from url=https://raw.githubusercontent.com/get-woke/woke/main/example.yaml
2023-02-17T09:31:35+01:00 DBG woke completed durationMS=0.430897
Error: Get "https://raw.githubusercontent.com/get-woke/woke/main/example.yaml": dial tcp: lookup raw.githubusercontent.com on [::1]:53: dial udp [::1]:53: socket: permission denied
Usage:
  < total print of help >
2023-02-17T09:31:35+01:00 FTL error="Get \"https://raw.githubusercontent.com/get-woke/woke/main/example.yaml\": dial tcp: lookup raw.githubusercontent.com on [::1]:53: dial udp [::1]:53: socket: permission denied"
```

It seems two [snap interfaces](https://snapcraft.io/docs/supported-interfaces) are missing to enable loading a config from the home directory and from internet:
- [personal-files](https://snapcraft.io/docs/personal-files-interface) to support hidden files in the home directory (for `~/.woke.yaml`).
- [network-interface](https://snapcraft.io/docs/network-interface) to access the network to download a remote config.

I don't have experience in building snaps yet, but looking at the config it seems that is a matter of adding the two interfaces in the list.

**Comment by degville** [comment]
Thanks so much for filing such a detailed report. And you were absolutely right about missing those two interfaces. I've now added them. Including `personal-files` triggers a manual review step; the Snap Store needs to check over this, so the build isn't yet available. I'll close this when it becomes accessible.

**Comment by nicorikken** [comment]
Thanks for the quick response. `personal-files` feels to be quite a big scope. Not sure if it can be scoped to specific files somehow. Regardless would be great if it works in this way.

**Edit:** I see you have scoped it in the config: https://github.com/degville/woke-snap/blob/7fcae9a6b3d166ade8d06ff94408b906005f23eb/snap/snapcraft.yaml#L17-L22

**Comment by nicorikken** [comment]
I noticed a small issue with the fix, see #2

**Comment by degville** [comment]
Access now requested on the forum: https://forum.snapcraft.io/t/personal-files-request-for-woke-snap/33969

**Comment by degville** [comment]
`personal-files` access has been granted to those files, and the snap has been published (currently in the _candidate_ channel, but I'll briefly test and promote to stable).

Thanks for your help with this.

**Comment by nicorikken** [comment]
I tested it and it works!
