### ISSUE TITLE
"permission denied" when trying to run the woke snap in our project documentation

### ISSUE THREAD

**Issue by pieqq** [degville/woke-snap#3]
Hello!

I'm trying to use the woke snap to check our project documentation. However, I get the following error when trying to run it:

```
$ woke
Error: open /home/pieq/dev/work/checkbox: permission denied
Usage:
  woke [globs ...] [flags]

Flags:
  -c, --config string           Config file (default is .woke.yaml in current directory, or $HOME)
      --debug                   Enable debug logging
      --disable-default-rules   Disable the default ruleset
      --exit-1-on-failure       Exit with exit code 1 on failures
  -h, --help                    help for woke
      --no-ignore               Ignored files in .gitignore, .ignore, .wokeignore, .git/info/exclude, and inline ignores are processed
  -o, --output string           Output type [text,simple,github-actions,json,sonarqube,checkstyle] (default "text")
      --stdin                   Read from stdin
  -v, --version                 version for woke

2023-06-13T11:32:06+08:00 FTL error="open /home/pieq/dev/work/checkbox: permission denied"
```

I've tried both the version in stable (`0.19.0-4-g5d52c15 2023-03-06 (20)`) and edge (`0.19.0-4-g5d52c15 2023-06-07 (21)`) channels, but it fails in both cases.

I've also tried using it the way it's setup in our Github action, but I get the same error:

```
$ woke *.rst **/*.rst -c https://github.com/canonical-web-and-design/Inclusive-naming/raw/main/config.yml
Error: open /home/pieq/dev/work/checkbox: permission denied
Usage:
  woke [globs ...] [flags]

Flags:
  -c, --config string           Config file (default is .woke.yaml in current directory, or $HOME)
      --debug                   Enable debug logging
      --disable-default-rules   Disable the default ruleset
      --exit-1-on-failure       Exit with exit code 1 on failures
  -h, --help                    help for woke
      --no-ignore               Ignored files in .gitignore, .ignore, .wokeignore, .git/info/exclude, and inline ignores are processed
  -o, --output string           Output type [text,simple,github-actions,json,sonarqube,checkstyle] (default "text")
      --stdin                   Read from stdin
  -v, --version                 version for woke

2023-06-13T11:36:58+08:00 FTL error="open /home/pieq/dev/work/checkbox: permission denied"
```

**Comment by degville** [comment]
Hello - thanks for reporting this. I've just tried your repo both locally (with `make woke`) and using your command from the docs directory, and it works for me. The latter does require the network interface to be connected:

```bash
sudo snap connect woke:network
```

**Comment by pieqq** [comment]
OK, turns out the directory where my project sits is in another disk which is mounted in `/mnt`. I had not realized initially because I use a symlink from my `$HOME`.

According to [snapcraft documentation](https://snapcraft.io/docs/removable-media-interface):

> removable-media allows read/write access to mounted removable storage in /media, /run/media and /mnt.

So after installing the latest version of the woke snap from the beta channel, all I had to do was to connect the `removable-media` slot:

```
snap install woke --beta
snap connect woke:removable-media
```

And now it works!

**Comment by degville** [comment]
Excellent, thanks for letting me know. I'll promote the beta and add some instructions for the interface!
